include: package:flutter_lints/flutter.yaml

linter:
  rules:
    lines_longer_than_80_chars: false
    avoid_dynamic_calls: true
    implementation_imports: false
    avoid_classes_with_only_static_members: false
    public_member_api_docs: false
    prefer_const_constructors: true
    avoid_print: true
    prefer_relative_imports: true
analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
