name: codeunion_test_task
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: ^3.0.0
  flutter: ^3.10.2

dependencies:
  auto_route: ^7.1.0
  bloc: ^8.1.2
  dio: ^5.2.1+1
  easy_localization: ^3.0.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.6
  formz: ^0.6.0
  get_it: ^7.2.0
  google_fonts: ^5.1.0
  json_annotation: ^4.5.0
  rxdart: ^0.27.4
  yaml: ^3.1.1

dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/translations/